name: Foo Parameterization CI

on: [push, pull_request]

jobs:

  Foo-CI:

    name: Python - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: foo-exercise

      - name: Build conda environment and run tests
        shell: bash -l {0}
        run: |

          echo " "
          echo "Installing conda environment"
          echo " "
          cd $RUNNER_WORKSPACE/
          cd foo_parameterization/
          $CONDA/bin/conda env update -f environment.yml -n foo-env

          echo " "
          echo "Installing foo_parameterization package"
          echo " "
          python setup.py develop

          echo " "
          echo "Testing package installation"
          echo " "
          python -c "import foo_parameterization; print('Version: ' + foo_parameterization.__version__); print('Path: ' + foo_parameterization.__path__[0])"

          echo " "
          echo "The conda environment being used:"
          echo " "
          $CONDA/bin/conda env export

          echo " "
          echo "Running pytests"
          echo " "
          pytest foo_parameterization/tests/
